# Generated by Django 4.1.1 on 2022-10-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='labmanual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_title', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=10)),
                ('objective', models.CharField(max_length=200)),
                ('ilos', models.CharField(max_length=200)),
                ('discussion', models.CharField(max_length=500)),
                ('res', models.CharField(max_length=100)),
                ('procedures', models.CharField(max_length=300)),
                ('questions', models.CharField(max_length=200)),
                ('supplementary', models.CharField(max_length=200)),
            ],
        ),
    ]
