# Generated by Django 4.1.1 on 2022-10-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmanual',
            name='act_no',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
