# Generated by Django 4.1.1 on 2022-10-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_labmanual_act_no_alter_labmanual_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmanual',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
