# Generated by Django 4.1.1 on 2022-10-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_labmanual_procedures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmanual',
            name='discussion',
            field=models.TextField(),
        ),
    ]
