# Generated by Django 4.1.1 on 2022-10-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_labmanual_ilos_alter_labmanual_objective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmanual',
            name='act_no',
            field=models.IntegerField(),
        ),
    ]
