# Generated by Django 4.1.1 on 2022-11-12 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_labmanual_act_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmanual',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
