# Generated by Django 4.1.1 on 2022-11-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_labmanual_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labmanual',
            name='author',
        ),
    ]
