# Generated by Django 4.1.1 on 2022-11-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_labmanual_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='labmanual',
            name='course_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
