# Generated by Django 4.1.1 on 2022-12-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_course_code_course_title_delete_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course_code',
            new_name='course_code_db',
        ),
        migrations.RenameModel(
            old_name='course_title',
            new_name='course_title_db',
        ),
    ]
