# Generated by Django 4.1.1 on 2022-12-04 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_course_code_course_code_db_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_title_db',
            name='code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.course_code_db'),
            preserve_default=False,
        ),
    ]
